// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {os} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SplitFile(arg1:os.File,arg2:number,arg3:string,arg4:boolean):Promise<void>;

export function SystemDirectorySelect():Promise<string>;

export function SystemFileSelect():Promise<string>;
